#!/bin/sh

PLATFORM="`uname`"

## MacPorts check
if [ "$PLATFORM" = "Darwin" ]; then
  if [ ! -d "/opt/local" ]; then
    echo "Must have MacPorts installed in default location to compile."
    exit 1;
  fi

  if [ ! -f "/opt/local/include/tiffio.h" ]; then
    sudo port install tiff
  fi

fi

## Comment out to compile release version.
DEBUG='-DDEBUG'

## Dynamic library version
if [ "$1" = "lib" ]; then
  if [ -f latwuc.o ]; then rm latwuc.o
    fi

  if [ -f latwuc.so ]; then rm latwuc.so
    fi

  if [ -f tiff_write_dyn ]; then rm tiff_write_dyn
    fi

  echo "Compiling dynamic library version."

  if [ "$PLATFORM" = "Darwin" ]; then
    clang -c -fpic latwuc.c -Wall -Wextra -I/opt/local/include -O3
    clang -shared -lc -o latwuc.so latwuc.o -L/opt/local/lib -ltiff
    clang -o tiff_write_dyn tiff_example_dyn.c -ldl -ltiff \
          -L. -L/opt/local/lib $DEBUG -DLIB -Wall -Wextra -O3
  elif [ "$PLATFORM" = "Linux" ]; then
    clang -c -fpic latwuc.c -Wall -Wextra -O3
    clang -shared -lc -o latwuc.so latwuc.o
    clang -o tiff_write_dyn tiff_example_dyn.c -ldl -ltiff -L. \
      $DEBUG -DLIB -Wall -Wextra -O3
  fi

  if [ -z "$LD_LIBRARY_PATH" ]; then
    echo "execute 'export LD_LIBRARY_PATH=`pwd`'"
  fi

# Include file version.
else
  if [ -f tiff_write_static ]; then rm tiff_write_static
    fi

  echo "Compiling static verson."

  if [ "$PLATFORM" = "Darwin" ]; then
    clang -otiff_write_static tiff_example_include.c latwuc.c -ltiff \
      -I/opt/local/include -L/opt/local/lib $DEBUG -Wall -Wextra -O3
  elif [ "$PLATFORM" = "Linux" ]; then
    clang -otiff_write_static tiff_example_include.c latwuc.c -ltiff $DEBUG \
      -Wall -Wextra -O3
  fi
fi
